import { createClient } from "@sanity/client";

const client = createClient({
  projectId: "o2kvv3c9",
  dataset: "production",
  apiVersion: "2024-01-01",
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
});

interface Room {
  _type: "room";
  _key: string;
  name: string;
  description: string;
  viewType: "sea-view" | "mountain-view" | "no-view";
  capacity: number;
  priceWeekday: number;
  priceWeekend: number;
  priceHoliday: number;
}

interface Property {
  _id: string;
  _type: "property";
  name: string;
  slug: { _type: "slug"; current: string };
  category: "villa" | "hotel";
  rooms: Room[];
  order: number;
}

function toSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function parseViewType(
  category: string,
): "sea-view" | "mountain-view" | "no-view" {
  if (category.includes("View biển")) return "sea-view";
  if (category.includes("View núi")) return "mountain-view";
  return "no-view";
}

const properties: Property[] = [
  {
    _id: "property-homestay-lamer",
    _type: "property",
    name: "Homestay Lamer",
    slug: { _type: "slug", current: "homestay-lamer" },
    category: "hotel",
    order: 1,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "Phòng số 1",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 900000,
        priceWeekend: 1100000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "Phòng số 2",
        description: "1 giường tầng, không view",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1400000,
        priceHoliday: 1800000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "Phòng số 3",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 1000000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "Phòng số 4",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 1000000,
      },
      {
        _type: "room",
        _key: "r5",
        name: "Phòng số 5",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 900000,
        priceWeekend: 1100000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r6",
        name: "Phòng số 6",
        description: "2 giường tầng, không view",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1400000,
        priceHoliday: 1800000,
      },
    ],
  },
  {
    _id: "property-homestay-lang-chai",
    _type: "property",
    name: "Homestay Làng Chài",
    slug: { _type: "slug", current: "homestay-lang-chai" },
    category: "hotel",
    order: 2,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "P101",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "P102",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "P201",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "P202",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r5",
        name: "P103",
        description: "View núi 1 giường",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 1400000,
        priceWeekend: 1000000,
        priceHoliday: 1300000,
      },
      {
        _type: "room",
        _key: "r6",
        name: "P110",
        description: "Không view",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 1400000,
        priceWeekend: 1000000,
        priceHoliday: 1300000,
      },
      {
        _type: "room",
        _key: "r7",
        name: "P203",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 450000,
        priceWeekend: 550000,
        priceHoliday: 700000,
      },
      {
        _type: "room",
        _key: "r8",
        name: "P205",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 450000,
        priceWeekend: 550000,
        priceHoliday: 700000,
      },
      {
        _type: "room",
        _key: "r9",
        name: "P206",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 450000,
        priceWeekend: 550000,
        priceHoliday: 700000,
      },
      {
        _type: "room",
        _key: "r10",
        name: "P212",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 450000,
        priceWeekend: 550000,
        priceHoliday: 700000,
      },
      {
        _type: "room",
        _key: "r11",
        name: "P104",
        description: "View núi 1 giường - rộng",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 1100000,
        priceWeekend: 1400000,
        priceHoliday: 1800000,
      },
      {
        _type: "room",
        _key: "r12",
        name: "P109",
        description: "View núi 1 giường",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 1100000,
        priceWeekend: 1400000,
        priceHoliday: 1800000,
      },
      {
        _type: "room",
        _key: "r13",
        name: "P204",
        description: "View núi 1 giường",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r14",
        name: "P207",
        description: "View núi 1 giường",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r15",
        name: "P208",
        description: "View núi 1 giường",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1500000,
      },
      {
        _type: "room",
        _key: "r16",
        name: "P211",
        description: "View núi 1 giường",
        viewType: "mountain-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r17",
        name: "P107",
        description: "View núi 2 giường",
        viewType: "mountain-view",
        capacity: 4,
        priceWeekday: 1300000,
        priceWeekend: 1600000,
        priceHoliday: 2000000,
      },
      {
        _type: "room",
        _key: "r18",
        name: "P108",
        description: "View núi 2 giường",
        viewType: "mountain-view",
        capacity: 4,
        priceWeekday: 1300000,
        priceWeekend: 1600000,
        priceHoliday: 2000000,
      },
      {
        _type: "room",
        _key: "r19",
        name: "P209",
        description: "Không view 2 giường",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1300000,
        priceHoliday: 1500000,
      },
      {
        _type: "room",
        _key: "r20",
        name: "P210",
        description: "Không view 2 giường",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1300000,
        priceHoliday: 1500000,
      },
      {
        _type: "room",
        _key: "r21",
        name: "P105",
        description: "Không view 2 giường",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1400000,
        priceHoliday: 1700000,
      },
      {
        _type: "room",
        _key: "r22",
        name: "P106",
        description: "1 giường đôi, 1 giường tầng",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1500000,
        priceWeekend: 1800000,
        priceHoliday: 2100000,
      },
    ],
  },
  {
    _id: "property-xom-chai",
    _type: "property",
    name: "Xóm Chài",
    slug: { _type: "slug", current: "xom-chai" },
    category: "hotel",
    order: 3,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "C1",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "C2",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "C3",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "C4",
        description: "View biển có ban công",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
      {
        _type: "room",
        _key: "r5",
        name: "C5",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r6",
        name: "C6",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r7",
        name: "C7",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r8",
        name: "C8",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r9",
        name: "C9",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r10",
        name: "C10",
        description: "Không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r11",
        name: "Sỏi",
        description: "Villa mini",
        viewType: "sea-view",
        capacity: 4,
        priceWeekday: 1200000,
        priceWeekend: 1400000,
        priceHoliday: 1600000,
      },
      {
        _type: "room",
        _key: "r12",
        name: "Cát",
        description: "Villa mini",
        viewType: "sea-view",
        capacity: 4,
        priceWeekday: 1200000,
        priceWeekend: 1400000,
        priceHoliday: 1600000,
      },
      {
        _type: "room",
        _key: "r13",
        name: "Đá",
        description: "Villa mini",
        viewType: "sea-view",
        capacity: 4,
        priceWeekday: 1200000,
        priceWeekend: 1400000,
        priceHoliday: 1600000,
      },
      {
        _type: "room",
        _key: "r14",
        name: "San hô",
        description: "Villa mini",
        viewType: "sea-view",
        capacity: 4,
        priceWeekday: 1200000,
        priceWeekend: 1400000,
        priceHoliday: 1600000,
      },
    ],
  },
  {
    _id: "property-xom-luoi-tang-2",
    _type: "property",
    name: "Xóm Lưới (Tầng 2)",
    slug: { _type: "slug", current: "xom-luoi-tang-2" },
    category: "hotel",
    order: 4,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "Ốc",
        description: "3 giường, có ban công",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 1800000,
        priceWeekend: 2200000,
        priceHoliday: 2600000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "Sò",
        description: "2 giường, có ban công",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1400000,
        priceWeekend: 1700000,
        priceHoliday: 2100000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "Cua",
        description: "2 giường, không view",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1300000,
        priceHoliday: 1500000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "Ghẹ",
        description: "2 giường, không view",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1300000,
        priceHoliday: 1500000,
      },
      {
        _type: "room",
        _key: "r5",
        name: "Tôm",
        description: "1 giường, có ban công",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 800000,
        priceWeekend: 1000000,
        priceHoliday: 1200000,
      },
      {
        _type: "room",
        _key: "r6",
        name: "Nhum",
        description: "1 giường, có ban công",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 800000,
        priceWeekend: 1000000,
        priceHoliday: 1200000,
      },
      {
        _type: "room",
        _key: "r7",
        name: "Mực",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r8",
        name: "Hàu",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
    ],
  },
  {
    _id: "property-xom-luoi-tang-3",
    _type: "property",
    name: "Xóm Lưới (Tầng 3)",
    slug: { _type: "slug", current: "xom-luoi-tang-3" },
    category: "hotel",
    order: 5,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "Cá Cờ",
        description: "3 giường, có ban công view biển",
        viewType: "sea-view",
        capacity: 6,
        priceWeekday: 1800000,
        priceWeekend: 2200000,
        priceHoliday: 2600000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "Cá Thu",
        description: "2 giường, có ban công view biển",
        viewType: "sea-view",
        capacity: 4,
        priceWeekday: 1400000,
        priceWeekend: 1700000,
        priceHoliday: 2100000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "Cá Nục",
        description: "2 giường, không view",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1300000,
        priceHoliday: 1500000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "Cá Chim",
        description: "2 giường, không view",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1100000,
        priceWeekend: 1300000,
        priceHoliday: 1500000,
      },
      {
        _type: "room",
        _key: "r5",
        name: "Cá Bóp",
        description: "1 giường, có ban công view biển",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 800000,
        priceWeekend: 1000000,
        priceHoliday: 1200000,
      },
      {
        _type: "room",
        _key: "r6",
        name: "Cá Mú",
        description: "1 giường, có ban công view biển",
        viewType: "sea-view",
        capacity: 2,
        priceWeekday: 800000,
        priceWeekend: 1000000,
        priceHoliday: 1200000,
      },
      {
        _type: "room",
        _key: "r7",
        name: "Cá Nhồng",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
      {
        _type: "room",
        _key: "r8",
        name: "Cá Trích",
        description: "1 giường, không view",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 600000,
        priceWeekend: 700000,
        priceHoliday: 900000,
      },
    ],
  },
  {
    _id: "property-xom-luoi-tang-4",
    _type: "property",
    name: "Xóm Lưới (Tầng 4)",
    slug: { _type: "slug", current: "xom-luoi-tang-4" },
    category: "hotel",
    order: 6,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "Bào Ngư",
        description: "2 phòng ngủ, 2 toilet, view biển + núi",
        viewType: "sea-view",
        capacity: 8,
        priceWeekday: 2200000,
        priceWeekend: 2500000,
        priceHoliday: 3000000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "Sao Biển",
        description: "2 phòng ngủ, 2 toilet, view biển + núi",
        viewType: "sea-view",
        capacity: 6,
        priceWeekday: 1900000,
        priceWeekend: 2300000,
        priceHoliday: 2700000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "Bạch Tuộc",
        description: "2 phòng ngủ, 2 toilet, view biển + núi",
        viewType: "sea-view",
        capacity: 6,
        priceWeekday: 1900000,
        priceWeekend: 2300000,
        priceHoliday: 2700000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "Ngọc Trai",
        description: "2 phòng ngủ, 1 toilet, view biển",
        viewType: "sea-view",
        capacity: 4,
        priceWeekday: 1600000,
        priceWeekend: 1900000,
        priceHoliday: 2300000,
      },
    ],
  },
  {
    _id: "property-villa",
    _type: "property",
    name: "Villa La Mer",
    slug: { _type: "slug", current: "villa-la-mer" },
    category: "villa",
    order: 7,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "Villa Chài",
        description: "",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 3000000,
        priceWeekend: 3200000,
        priceHoliday: 3600000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "Villa Lưới",
        description: "",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 3000000,
        priceWeekend: 3200000,
        priceHoliday: 3600000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "Villa Thuyền",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 4000000,
        priceWeekend: 4500000,
        priceHoliday: 5500000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "Villa Thúng",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3500000,
        priceWeekend: 4000000,
        priceHoliday: 5000000,
      },
      {
        _type: "room",
        _key: "r5",
        name: "Villa Sóng",
        description: "",
        viewType: "no-view",
        capacity: 8,
        priceWeekday: 3500000,
        priceWeekend: 4000000,
        priceHoliday: 5000000,
      },
      {
        _type: "room",
        _key: "r6",
        name: "Villa Gió",
        description: "",
        viewType: "no-view",
        capacity: 10,
        priceWeekday: 4000000,
        priceWeekend: 4500000,
        priceHoliday: 5500000,
      },
      {
        _type: "room",
        _key: "r7",
        name: "Villa Nắng",
        description: "Không có bếp, sân rộng",
        viewType: "no-view",
        capacity: 16,
        priceWeekday: 6500000,
        priceWeekend: 7000000,
        priceHoliday: 8500000,
      },
      {
        _type: "room",
        _key: "r8",
        name: "Villa Biển",
        description: "Không có bếp",
        viewType: "no-view",
        capacity: 12,
        priceWeekday: 5500000,
        priceWeekend: 6000000,
        priceHoliday: 7000000,
      },
      {
        _type: "room",
        _key: "r9",
        name: "Villa Mây",
        description: "",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 4000000,
        priceWeekend: 4400000,
        priceHoliday: 5200000,
      },
      {
        _type: "room",
        _key: "r10",
        name: "Villa Hoa",
        description: "",
        viewType: "no-view",
        capacity: 12,
        priceWeekday: 4500000,
        priceWeekend: 5000000,
        priceHoliday: 6000000,
      },
      {
        _type: "room",
        _key: "r11",
        name: "Làng Em 1",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3500000,
        priceWeekend: 4000000,
        priceHoliday: 5000000,
      },
      {
        _type: "room",
        _key: "r12",
        name: "Làng Em 2",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3500000,
        priceWeekend: 4000000,
        priceHoliday: 5000000,
      },
      {
        _type: "room",
        _key: "r13",
        name: "Nhà Bà Hương",
        description: "",
        viewType: "no-view",
        capacity: 8,
        priceWeekday: 4000000,
        priceWeekend: 4500000,
        priceHoliday: 5500000,
      },
      {
        _type: "room",
        _key: "r14",
        name: "Nhà Bà Ngoại",
        description: "",
        viewType: "no-view",
        capacity: 15,
        priceWeekday: 6500000,
        priceWeekend: 7000000,
        priceHoliday: 8500000,
      },
      {
        _type: "room",
        _key: "r15",
        name: "Nhà Ông Ngoại",
        description: "",
        viewType: "no-view",
        capacity: 12,
        priceWeekday: 3800000,
        priceWeekend: 4500000,
        priceHoliday: 5500000,
      },
      {
        _type: "room",
        _key: "r16",
        name: "Nhà Như Ý",
        description: "",
        viewType: "no-view",
        capacity: 10,
        priceWeekday: 3000000,
        priceWeekend: 3500000,
        priceHoliday: 4200000,
      },
      {
        _type: "room",
        _key: "r17",
        name: "Nhà Hoa Đào",
        description: "Không bao gồm ăn sáng",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 1500000,
        priceWeekend: 2000000,
        priceHoliday: 2500000,
      },
      {
        _type: "room",
        _key: "r18",
        name: "Nhà Cá",
        description: "",
        viewType: "no-view",
        capacity: 4,
        priceWeekday: 1000000,
        priceWeekend: 1200000,
        priceHoliday: 1400000,
      },
    ],
  },
  {
    _id: "property-santo-villa",
    _type: "property",
    name: "Santo Villa",
    slug: { _type: "slug", current: "santo-villa" },
    category: "villa",
    order: 8,
    rooms: [
      {
        _type: "room",
        _key: "r1",
        name: "Santo San",
        description: "",
        viewType: "no-view",
        capacity: 8,
        priceWeekday: 4800000,
        priceWeekend: 6000000,
        priceHoliday: 7000000,
      },
      {
        _type: "room",
        _key: "r2",
        name: "Santo Ri",
        description: "",
        viewType: "no-view",
        capacity: 8,
        priceWeekday: 4800000,
        priceWeekend: 6000000,
        priceHoliday: 7000000,
      },
      {
        _type: "room",
        _key: "r3",
        name: "Santo Li",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 4000000,
        priceWeekend: 5000000,
        priceHoliday: 6000000,
      },
      {
        _type: "room",
        _key: "r4",
        name: "Santo Vi",
        description: "",
        viewType: "no-view",
        capacity: 2,
        priceWeekday: 1600000,
        priceWeekend: 2000000,
        priceHoliday: 2400000,
      },
      {
        _type: "room",
        _key: "r5",
        name: "Santo Si",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3000000,
        priceWeekend: 3200000,
        priceHoliday: 4000000,
      },
      {
        _type: "room",
        _key: "r6",
        name: "Santo Di",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3200000,
        priceWeekend: 3500000,
        priceHoliday: 4300000,
      },
      {
        _type: "room",
        _key: "r7",
        name: "Santo 7",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3000000,
        priceWeekend: 3200000,
        priceHoliday: 4000000,
      },
      {
        _type: "room",
        _key: "r8",
        name: "Santo 8",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3000000,
        priceWeekend: 3200000,
        priceHoliday: 4000000,
      },
      {
        _type: "room",
        _key: "r9",
        name: "Santo 9",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3200000,
        priceWeekend: 3500000,
        priceHoliday: 4300000,
      },
      {
        _type: "room",
        _key: "r10",
        name: "Santo 10",
        description: "",
        viewType: "no-view",
        capacity: 6,
        priceWeekday: 3200000,
        priceWeekend: 3500000,
        priceHoliday: 4300000,
      },
    ],
  },
];

async function seed() {
  console.log(`Seeding ${properties.length} properties...`);

  const transaction = client.transaction();

  for (const prop of properties) {
    transaction.createOrReplace(prop);
    console.log(
      `  + ${prop.name} (${prop.category}) - ${prop.rooms.length} rooms`,
    );
  }

  const result = await transaction.commit();
  console.log(`\nDone! ${result.documentIds.length} documents created.`);

  // Summary
  const totalRooms = properties.reduce((sum, p) => sum + p.rooms.length, 0);
  const villas = properties.filter((p) => p.category === "villa");
  const hotels = properties.filter((p) => p.category === "hotel");
  console.log(`\nSummary:`);
  console.log(
    `  Villa: ${villas.length} properties, ${villas.reduce((s, p) => s + p.rooms.length, 0)} rooms`,
  );
  console.log(
    `  Hotel: ${hotels.length} properties, ${hotels.reduce((s, p) => s + p.rooms.length, 0)} rooms`,
  );
  console.log(`  Total: ${properties.length} properties, ${totalRooms} rooms`);
}

seed().catch(console.error);
